services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=users_DB'
      - 'POSTGRES_PASSWORD=pingomaistro'
      - 'POSTGRES_USER=william'
    ports:
      - '5461:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
